export const industries = [
  { value: 'All', label: 'All', default: true },
  { value: 'Software Development', label: 'Software Development' },
  { value: 'Data Science', label: 'Data Science' },
  { value: 'Finance', label: 'Finance' },
  { value: 'Healthcare', label: 'Healthcare' },
  { value: 'Education', label: 'Education' },
  { value: 'E-commerce', label: 'E-commerce' },
  { value: 'Marketing', label: 'Marketing' },
  { value: 'Gaming', label: 'Gaming' },
  { value: 'Cybersecurity', label: 'Cybersecurity' },
  { value: 'Artificial Intelligence', label: 'Artificial Intelligence' },
  { value: 'DevOps', label: 'DevOps' },
  { value: 'Mobile Development', label: 'Mobile Development' },
  { value: 'Web Development', label: 'Web Development' },
  { value: 'Cloud Computing', label: 'Cloud Computing' },
  { value: 'Blockchain', label: 'Blockchain' },
  { value: 'Telecommunications', label: 'Telecommunications' },
  { value: 'Automotive', label: 'Automotive' },
  { value: 'Aerospace', label: 'Aerospace' },
  { value: 'Real Estate', label: 'Real Estate' },
  { value: 'Legal', label: 'Legal' },
  { value: 'Human Resources', label: 'Human Resources' },
  { value: 'Retail', label: 'Retail' },
  { value: 'Manufacturing', label: 'Manufacturing' },
  { value: 'Hospitality', label: 'Hospitality' },
  { value: 'Energy', label: 'Energy' },
  { value: 'Government', label: 'Government' },
  { value: 'Non-profit', label: 'Non-profit' },
  { value: 'Media & Entertainment', label: 'Media & Entertainment' },
  { value: 'Agriculture', label: 'Agriculture' }
];